[Settings]

ID = "wai-wcag-em-overview"

[build]

command = "bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[[redirects]]
  from = "/"
  to = "/test-evaluate/conformance/wcag-em/"